services:

  mysql:
    image: mysql
    expose:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  postgres:
    image: postgres
    expose:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: test
