# For the test on gibhub actions only

services:

  mysql:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  postgres:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: test
