src = ["src"]
extend-exclude = ["docs"]
# Always generate Python 3.7-compatible code.
target-version = "py37"
line-length = 128
ignore-init-module-imports = true
[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
# Ignore `F401`(imported but unused), `F403`(import *` used), `E402`(import violations) in all `__init__.py` files
[per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
